def DATA_TO_WRITE(Data):
    Erd_CurrentSystemState = Data[0]
    Erd_CurrentSystemState = {                                           
        0: "SystemState_StartUp",
        1: "SystemState_Idle",
        2: "SystemState_Standby",
        3: "SystemState_Run",
        4: "SystemState_Pause",
        5: "SystemState_EndOfCycle",
        6: "SystemState_DelayRun",
        7: "SystemState_DelayPause",
        8: "SystemState_Commissioning",
        9: "SystemState_Max"                               
    }.get(Erd_CurrentSystemState)  
    Erd_CycleSelected = Data[1]
    Erd_CycleSelected = {
        0:  "CycleSelected_NotDefined",
        1:  "CycleSelected_BasketClean",
        2:  "CycleSelected_DrainSpin",
        3:  "CycleSelected_QuickRinse",
        4:  "CycleSelected_BulkyItems",
        5:  "CycleSelected_Sanitize",
        6:  "CycleSelected_TowelsSheets",
        7:  "CycleSelected_WasherSteamRefresh",
        8:  "CycleSelected_NormalOrMixedLoad",
        9:  "CycleSelected_Whites",
        10: "CycleSelected_DarkColors",
        11: "CycleSelected_Jeans",
        12: "CycleSelected_HandWash",
        13: "CycleSelected_Delicates",
        14: "CycleSelected_SpeedWash",
        15: "CycleSelected_HeavyDuty",
        16: "CycleSelected_Allergen",
        17: "CycleSelected_PowerClean",
        18: "CycleSelected_RinseSpin",
        19: "CycleSelected_SingleItem",
        20: "CycleSelected_Colors",
        21: "CycleSelected_ColdWash",
        22: "CycleSelected_WaterOnDemand",
        23: "CycleSelected_TubClean",
        24: "CycleSelected_CasualsWithSteam",
        25: "CycleSelected_StainWashWithSteam",
        26: "CycleSelected_DeepClean",
        128: "CycleSelected_Cottons",
        129: "CycleSelected_EasyCare",
        130: "CycleSelected_ActiveWear",
        131: "CycleSelected_TimedDry",
        132: "CycleSelected_DeWrinkle",
        133: "CycleSelected_Airfluff",
        134: "CycleSelected_SteamRefresh",
        135: "CycleSelected_SteamDewrinkle",
        136: "CycleSelected_SpeedDry",
        137: "CycleSelected_Mixed",
        138: "CycleSelected_QuickDry",
        139: "CycleSelected_Casuals",
        140: "CycleSelected_WarmUp",
        141: "CycleSelected_EnergySaver",
        142: "CycleSelected_Antibacterial",
        143: "CycleSelected_RackDry",
        144: "CycleSelected_BabyCare",
        145: "CycleSelected_AutoDry",
        146: "CycleSelected_TimedDryWithNoHeat",
        147: "CycleSelected_PermPress",
        148: "CycleSelected_WasherLink"
    }

DATA_TO_WRITE([10, 10])